[package]
name = "rtrk"
version = "0.1.0"
edition = "2021"
authors = ["Anders Sundman <anders@4zm.org>"]
license = "GPL-3.0"

[dependencies]
crossterm = "0.28.1"
itertools = "0.14.0"
rodio = "0.20.1"
